language: java
env:
  global:
    - SONATYPE_THIRDPARTY_SERVER=cna-thirdparty
    - SONATYPE_USERNAME=deployment
    - secure: "NHgpc7vC7QnKeMje/Y7ph5vWE27uIzqYDh8l6z5q5LwdtAH29v4Ef2NGvo8F\nHK/Urz+wmZe20VZ/mv2goEZ5Ta0ANs5ULIR3CHycNkFwNQFkOO8X+AYNG2HT\nqqznTcm1s7lOqmrIu+RJ1+CU+VKsA9l8LbR8PtF+SJeea0lWZFU="
    
after_script:
  - python .mvnSettings.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml
